### ISSUE TITLE
Removal of cardano_node_metrics_connectedPeers_int from metrics

### ISSUE THREAD

**Issue by AlexanderNorris** [Crypto2099/simpleLiveView#1]
As of upgrading to Cardano Node 1.25.1 I have noticed that the metrics for cardano_node_metrics_connectedPeers_int have been removed from the Prometheus metrics. This is causing the connected $peers variable not to be set. This does not affect $remotepeers as this setting is determined by netstat.

**Comment by Crypto2099** [comment]
This has not been removed, you need to turn on the "TraceBlockFetchDecisions" trace in your mainnet-config.json to enable reporting of the outbound connected peers in the Prometheus metrics which simpleLiveView uses to display.

**Comment by AlexanderNorris** [comment]
Yep this issue can be closed, thank you very much for the quick response. 

Can I confirm are there any other defaults that need changing? Also perhaps it would be nice to include this in the README.md?

**Comment by Crypto2099** [comment]
There shouldn't be any other defaults from the config that require changes but this is a good point and I will add it to README. Thanks for the idea/suggestion!
